// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsoBiMF2nhorZ1PelnYa8Ggifd41hZEQ8',
    appId: '1:797510119091:web:6e2a7fcc54d4bdf33a8ac6',
    messagingSenderId: '797510119091',
    projectId: 'quiz101-11f8c',
    authDomain: 'quiz101-11f8c.firebaseapp.com',
    storageBucket: 'quiz101-11f8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLNlKHkxBpkvYIKh3fF_rOcD8Kjseka10',
    appId: '1:797510119091:android:cb4bc323c1a461c93a8ac6',
    messagingSenderId: '797510119091',
    projectId: 'quiz101-11f8c',
    storageBucket: 'quiz101-11f8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT_wdOuOB3GWpVUTTd-rD6qW5AyRXryao',
    appId: '1:797510119091:ios:7791b5071f595e2b3a8ac6',
    messagingSenderId: '797510119091',
    projectId: 'quiz101-11f8c',
    storageBucket: 'quiz101-11f8c.firebasestorage.app',
    iosBundleId: 'com.example.quiz101',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT_wdOuOB3GWpVUTTd-rD6qW5AyRXryao',
    appId: '1:797510119091:ios:7791b5071f595e2b3a8ac6',
    messagingSenderId: '797510119091',
    projectId: 'quiz101-11f8c',
    storageBucket: 'quiz101-11f8c.firebasestorage.app',
    iosBundleId: 'com.example.quiz101',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsoBiMF2nhorZ1PelnYa8Ggifd41hZEQ8',
    appId: '1:797510119091:web:36f8e0af15753e1f3a8ac6',
    messagingSenderId: '797510119091',
    projectId: 'quiz101-11f8c',
    authDomain: 'quiz101-11f8c.firebaseapp.com',
    storageBucket: 'quiz101-11f8c.firebasestorage.app',
  );
}
